name: adblocker_core
description: "Core package for adblocker webview"
version: 1.1.0
homepage: "https://github.com/islamdidarmd/flutter_adblocker_webview"

environment:
  sdk: 3.5.0 

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter


